version: '3.9'
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map React app to localhost:3000
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map Node.js server to localhost:5000
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
