title: "PhyloNext"
description: "PhyloNext v2 web-GUI documentation"

baseurl: "/phylonext_v2"
url: "https://vmikk.github.io"

# Exclude unnecessary files and directories
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - yarn.lock
  - README.md
  - Dockerfile

# Theme settings
theme: minima
plugins:
  - jekyll-seo-tag
